"""
Definición de estados conceptuales, operativos y reservados de la máquina de estados del caso.
"""

from enum import Enum
from typing import Set


class CaseState(str, Enum):
    """Todos los estados conceptuales reconocidos por el sistema."""

    NEW = "NEW"
    IDENTIFICATION_PENDING = "IDENTIFICATION_PENDING"
    IDENTIFICATION_COMPLETED = "IDENTIFICATION_COMPLETED"
    ACQUISITION_READY = "ACQUISITION_READY"
    ACQUIRING = "ACQUIRING"
    ACQUISITION_COMPLETED = "ACQUISITION_COMPLETED"
    ACQUISITION_VERIFIED = "ACQUISITION_VERIFIED"
    ANALYSIS_PENDING = "ANALYSIS_PENDING"
    PROCESSING_AXIOM = "PROCESSING_AXIOM"
    ANALYSIS_COMPLETED = "ANALYSIS_COMPLETED"
    RESULTS_PENDING = "RESULTS_PENDING"
    PORTABLE_CREATED = "PORTABLE_CREATED"
    REPORT_PENDING = "REPORT_PENDING"
    REPORT_GENERATED = "REPORT_GENERATED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    ABORTED = "ABORTED"


class OperativeState(str, Enum):
    """Estados operativos habilitados activamente en Sprint R08.1."""

    NEW = "NEW"
    IDENTIFICATION_PENDING = "IDENTIFICATION_PENDING"
    IDENTIFICATION_COMPLETED = "IDENTIFICATION_COMPLETED"
    ACQUISITION_READY = "ACQUISITION_READY"
    ACQUIRING = "ACQUIRING"
    ACQUISITION_COMPLETED = "ACQUISITION_COMPLETED"
    FAILED = "FAILED"
    ABORTED = "ABORTED"


class ReservedState(str, Enum):
    """Estados reservados para fases o sprints futuros (R09+)."""

    ACQUISITION_VERIFIED = "ACQUISITION_VERIFIED"
    ANALYSIS_PENDING = "ANALYSIS_PENDING"
    PROCESSING_AXIOM = "PROCESSING_AXIOM"
    ANALYSIS_COMPLETED = "ANALYSIS_COMPLETED"
    RESULTS_PENDING = "RESULTS_PENDING"
    PORTABLE_CREATED = "PORTABLE_CREATED"
    REPORT_PENDING = "REPORT_PENDING"
    REPORT_GENERATED = "REPORT_GENERATED"
    COMPLETED = "COMPLETED"


TERMINAL_STATES: Set[CaseState] = {
    CaseState.COMPLETED,
    CaseState.ABORTED,
}
